### ISSUE TITLE
auth api rate limit and ip blocking

### ISSUE THREAD

**Issue by Nobody9512** [sail-host/cloud#42]

**Comment by Abbosbek-cloud** [comment]
Implemented rate limiter in my [#43](https://github.com/sail-host/cloud/pull/43) PR.

**Comment by Nobody9512** [comment]
Remove global rate limit. Only add auth routes.

**Comment by Abbosbek-cloud** [comment]
> Remove global rate limit. Only add auth routes.

RateLimiter moved into auth group router
